### ISSUE TITLE
Quest 2 Demo

### ISSUE THREAD

**Issue by bobbyreed** [bobbyreed/PlayingForKeeps#12]
- Android Build first

**Comment by Developer-Lion** [comment]
what is the update on the demo build?

**Comment by Developer-Lion** [comment]
This comment was solely to say I have put something on GitHub and feel cool lol

**Comment by bobbyreed** [comment]
It is my next goal! Glad to see you using the issues! Once I have a demo to you, we will start using `discussions` to capture our conversations in the repo.

**Comment by bobbyreed** [comment]
Release upload imminent
